Repository singodiyashubham87/Draw-it-out, pull requests merged in 2024-06, with the labels that each got.

#231 Guidelines visibility in dark mode (Fix Issue #207)
  src/App.jsx
  tailwind.config.js
Labels: bug, gssoc, level1

#255 Fixed #137:Resolving pen stroke feature
  src/components/Menu.jsx
Labels: gssoc, level2

#269 Added the logo
  src/assets/images/readmeLogo.png
  src/assets/images/webLogo.png
Labels: gssoc, level1

#279 Bug solved: Persistent Drawing After Exiting Canvas #268
  src/utils/canvas.js
Labels: ssoc, beginner

#235 alignment needs to done in multiple color section
  src/components/BgColorSidePanel.jsx
Labels: gssoc, level1

#266 chore: Disable prop-types rule in ESLint configuration, cleanup code
  .eslintrc.cjs
  src/components/BgColorSidePanel.jsx
  src/components/DrawingShapes.jsx
  src/components/Footer.jsx
  src/components/Menu.jsx
  src/utils/canvas.js
Labels: ssoc, beginner

#267 fix: improper scrolling behaviour by changing joyride placement
  src/utils/helpers.js
Labels: gssoc, level1

#294 [BUG:] Increase Height Button is Not Working
  src/utils/canvas.js
Labels: gssoc, level2

#324 cursor style changed
  src/App.jsx
Labels: gssoc

#284 [BUG]: Pen Drawing not working after selecting Shapes #188
  src/components/DrawingShapes.jsx
  src/components/Menu.jsx
Labels: bug, gssoc, level2

#336 components/chatbot: change font color for 'End Chat'
  src/components/Chatbot/Chatbot.jsx
Labels: gssoc

#338 The favicon of the website has been changed.
  README.md
  index.html
  src/assets/images/logo.png
Labels: gssoc

#351 [DOCS] Addition of no of forks star issue closed open pr to readme.md
  README.md
Labels: gssoc

#357 Update Footer.jsx
  src/components/Footer.jsx
Labels: gssoc

#369 [Feature Request]: Style added to Scrollbar
  src/index.css
Labels: enhancement, gssoc, level1

#378 moved the guideline button to right for better flow
  src/App.jsx
Labels: gssoc, level1

#347 Issue#332: Disabled text-selection.
  src/index.css
  src/main.jsx
Labels: gssoc

#350 Responsiveness
  src/App.jsx
  src/components/BgColorSidePanel.jsx
  src/components/Menu.jsx
  src/index.css
Labels: gssoc, level2

#395 Added Icons
  src/components/Footer.jsx
Labels: gssoc, level1

#394 fix(footer): chatbot alignment adjusted
  src/components/Chatbot/Chatbot.jsx
Labels: gssoc, level1

#412 [BUG] : Resposive Missing
  src/components/Footer.jsx
Labels: gssoc, level1

#410 Added individual hover effect on shapes
  src/components/DrawingShapes.jsx
Labels: enhancement, gssoc, level1

#416 Update Menu.jsx
  src/components/Menu.jsx
Labels: gssoc, level1

#263 fixes #142 (App.jsx, BgColorSidePanel.jsx, canvas.js): The line draw…
  src/App.jsx
  src/components/BgColorSidePanel.jsx
  src/utils/canvas.js
Labels: gssoc, level2

#422 Fixed the pen dropdown visiblity in dark mode
  src/components/Menu.jsx
Labels: gssoc, level1
