Repository singodiyashubham87/Draw-it-out, pull requests merged in 2024-05, with the labels that each got.

#90 fixed the [BUG] Unstable UI on mobile devices while drawing on white board #64
  src/utils/canvas.js
Labels: gssoc, level2

#96 closes Issue #76
  src/App.jsx
Labels: gssoc

#75 feat: Export to PDF and SVG
  package-lock.json
  package.json
  src/components/Menu.jsx
  src/utils/canvas.js
Labels: gssoc, level3

#102 Ref: #70 [Added a "Buy me a coffee" button]
  src/App.jsx
Labels: gssoc, level1

#95 rainbow background color"
  src/App.jsx
Labels: gssoc, level1

#115 [feat]:hover-on-color-icons
  src/components/BgColor.jsx
Labels: gssoc, level1

#116 [Bug] : Responsive Fixes
  src/index.css
Labels: bug, gssoc, level1

#129 Fixed #2: Resolved the issue of screen getting cleared on changing the pen stroke or color
  src/App.jsx
  src/components/Menu.jsx
  src/utils/canvas.js
Labels: bug, gssoc, level1

#125 Added a Walk Through
  package-lock.json
  package.json
  src/App.jsx
  src/components/Menu.jsx
Labels: enhancement, gssoc, level3

#110 Create greetings.yaml #98
  .github/workflows/greetings.yaml
Labels: enhancement, gssoc, level1

#131 Added the Dark/light mode functionality
  src/App.jsx
  src/components/BgColor.jsx
  src/components/Menu.jsx
  tailwind.config.js
Labels: enhancement, gssoc, level3

#134 fixed the breakpoint issue on tablets
  src/App.jsx
Labels: bug, gssoc, level1

#139 jpg, png export types now available
  src/components/Menu.jsx
  src/utils/canvas.js
Labels: enhancement, gssoc, level1

#153 Slove Write Installation Guide #31
  README.md
Labels: documentation, gssoc, level1

#151 Add brush strokes
  src/App.jsx
  src/components/Menu.jsx
  src/utils/canvas.js
Labels: gssoc, level2

#157 Fixed drawing while brush outside
  src/utils/canvas.js
Labels: bug, gssoc, level1

#154 [FEAT]: Implement Shape Drawing Tools #33
  package-lock.json
  package.json
  src/assets/images/circle.png
  src/assets/images/circle.svg
  src/assets/images/rectangle.svg
  src/assets/images/triangle.svg
  src/components/DrawingShapes.jsx
  src/components/Menu.jsx
Labels: enhancement, gssoc, level3

#160 Fixed the button
  package-lock.json
  package.json
  src/App.jsx
Labels: enhancement, gssoc

#126 Heading tagline guidelines
  package-lock.json
  package.json
  src/App.jsx
  src/index.css
Labels: enhancement, gssoc, level2

#150 Added Footer with Social Media Icons
  src/App.jsx
  src/assets/images/GMail.webp
  src/assets/images/X.png
  src/assets/images/github.png
  src/assets/images/linkedin.jpg
  src/components/Footer.jsx
Labels: enhancement, gssoc, level1

#200 Added responsiveness to Menu bar
  src/App.jsx
  src/assets/images/GMail.webp
  src/assets/images/X.png
  src/assets/images/github.png
  src/assets/images/linkedin.jpg
  src/components/BgColor.jsx
  src/components/BgColorSidePanel.jsx
  src/components/DrawingShapes.jsx
  src/components/Footer.jsx
  src/components/Menu.jsx
Labels: bug, gssoc, level2
