Repository singodiyashubham87/Draw-it-out, pull requests merged in 2024-07, with the labels that each got.

#428 Added the auto dropdown close feature
  src/components/DrawingShapes.jsx
Labels: gssoc, level1

#429 Adding aspect ratio feature
  src/App.jsx
  src/components/Menu.jsx
  src/index.css
  src/utils/canvas.js
Labels: gssoc, level2

#442 Fixed the start tour/tutorial
  src/App.jsx
  src/components/Menu.jsx
  src/utils/helpers.js
Labels: gssoc, level1

#452 Buy me coffee icon visible in dark mode
  src/App.jsx
Labels: gssoc, level1

#433 Made The Website "Canvas Responsive"
  src/App.jsx
Labels: gssoc, level2

#454 Fix Minimum width for the whiteboard
  src/index.css
  src/utils/canvas.js
Labels: gssoc

#359 Added dockerfile and docker-compose
  Dockerfile
  README.md
  package.json
  vite.config.js
Labels: gssoc, level2

#453 Enhanced Readme.md
  README.md
  src/assets/images/Gssoc Label.png
Labels: gssoc

#451 feat: Adding the other strokes button for different types of brushes
  package-lock.json
  src/App.jsx
  src/components/DrawingShapes.jsx
Labels: gssoc, level2

#463 Hover effects on footer made
  src/components/Footer.jsx
  src/components/FooterLink.jsx
Labels: gssoc, level1

#460 Added "Cursor Trail Effect" To Look More Artistic
  index.html
  package.json
  src/components/CursorTrailEffect.jsx
  src/main.jsx
Labels: gssoc, level2

#482 Add hover effect to social media icons
  package-lock.json
  src/components/Footer.jsx
  tailwind.config.js
Labels: gssoc, level1

#483 Added minor transition effect.
  src/index.css
Labels: gssoc, level1

#484 fixed footer in mobile view
  src/components/Footer.jsx
Labels: gssoc, level1

#485 Hide the Cursor Trail Effect in Mobile View
  src/components/CursorTrailEffect.jsx
Labels: gssoc, level1

#492 Fixed responsiveness issue of toolbar
  src/components/Menu.jsx
Labels: gssoc, level1

#500 contact as well as contribution added
  package-lock.json
  package.json
  src/App.jsx
  src/components/Contact/Contact.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Home.jsx
  src/components/Team/Contributor.jsx
Labels: gssoc, level2
